// Summarization provider: turns a transcript into structured meeting notes.
// OpenAI implementation uses JSON-mode chat completion; a mock keeps the flow
// working with no key.

import { useSettings } from "../../store/settingsStore";
import { inTauri } from "../tauri";
import { chatCompletion } from "./chat";
import type { Summary } from "../types";

export interface SummaryActionItem {
  owner: string;
  task: string;
  due?: string;
}

export interface SummaryResult {
  summary: Summary;
  actionItems: SummaryActionItem[];
  inputTokens?: number;
  outputTokens?: number;
  estimated: boolean;
}

export interface TranscriptLine {
  speaker: string;
  text: string;
}

export interface Summarizer {
  providerId: string;
  modelId: string;
  summarize(transcript: TranscriptLine[], title: string): Promise<SummaryResult>;
}

const SYSTEM_PROMPT =
  "You are an expert meeting-notes assistant. You read a meeting transcript and " +
  "produce concise, accurate notes. Respond with ONLY a raw JSON object — no " +
  "markdown, no code fences. Only include items that are actually supported by " +
  "the transcript; use empty arrays when there is nothing to report.";

function buildUserPrompt(transcript: TranscriptLine[], title: string): string {
  const lines = transcript.map((t) => `${t.speaker}: ${t.text}`).join("\n");
  return `Meeting title: ${title}

Transcript:
${lines}

Return a JSON object with EXACTLY this shape:
{
  "summary": "2-4 sentence executive summary",
  "decisions": ["short decision", ...],
  "risks": ["short risk", ...],
  "openQuestions": ["open question", ...],
  "nextAgenda": ["agenda item for next time", ...],
  "actionItems": [{"owner": "person or empty string", "task": "what to do", "due": "e.g. Fri or empty string"}]
}`;
}

function normalizeSummary(raw: any): { summary: Summary; actionItems: SummaryActionItem[] } {
  const arr = (v: any): string[] => (Array.isArray(v) ? v.filter((x) => typeof x === "string") : []);
  const summary: Summary = {
    executive: typeof raw?.summary === "string" ? raw.summary : "",
    decisions: arr(raw?.decisions),
    risks: arr(raw?.risks),
    openQuestions: arr(raw?.openQuestions),
    nextAgenda: arr(raw?.nextAgenda),
  };
  const actionItems: SummaryActionItem[] = Array.isArray(raw?.actionItems)
    ? raw.actionItems
        .filter((a: any) => a && typeof a.task === "string" && a.task.trim())
        .map((a: any) => ({
          owner: typeof a.owner === "string" ? a.owner : "",
          task: a.task,
          due: typeof a.due === "string" && a.due.trim() ? a.due : undefined,
        }))
    : [];
  return { summary, actionItems };
}

class OpenAISummarizer implements Summarizer {
  providerId = "openai";
  constructor(
    public modelId: string,
    private apiKey: string,
  ) {}

  async summarize(transcript: TranscriptLine[], title: string): Promise<SummaryResult> {
    const out = await chatCompletion(
      this.modelId,
      this.apiKey,
      SYSTEM_PROMPT,
      buildUserPrompt(transcript, title),
      true,
    );
    let parsed: any = {};
    try {
      parsed = JSON.parse(out.content);
    } catch {
      // Best effort: pull the first {...} block if the model wrapped it.
      const match = out.content.match(/\{[\s\S]*\}/);
      if (match) parsed = JSON.parse(match[0]);
    }
    const { summary, actionItems } = normalizeSummary(parsed);
    return {
      summary,
      actionItems,
      inputTokens: out.inputTokens,
      outputTokens: out.outputTokens,
      estimated: false,
    };
  }
}

class MockSummarizer implements Summarizer {
  providerId = "mock";
  constructor(public modelId: string) {}

  async summarize(transcript: TranscriptLine[], _title: string): Promise<SummaryResult> {
    const preview = transcript.slice(0, 3).map((t) => t.text).join(" ");
    return {
      summary: {
        executive: transcript.length
          ? `Mock summary — the real notes are generated by an LLM once an API key is set. Discussed ${transcript.length} segments. ${preview}`
          : "No transcript was captured.",
        decisions: [],
        risks: [],
        openQuestions: [],
        nextAgenda: [],
      },
      actionItems: [],
      estimated: true,
    };
  }
}

export function getSummarizer(): Summarizer {
  const { chatProvider, chatModel, apiKeys } = useSettings.getState();
  const key = apiKeys[chatProvider]?.trim();
  if (inTauri() && chatProvider === "openai" && key) {
    return new OpenAISummarizer(chatModel, key);
  }
  return new MockSummarizer(chatModel);
}
